### ISSUE TITLE
A mistake in README file

### ISSUE THREAD

**Issue by Neustradamus** [rcpacini/labview_hashlib#1]
@rcpacini: I wish you a Happy New Year!

There is a mistake in the README, the RFC for SCRAM-SHA-256 is 7677:
- https://datatracker.ietf.org/doc/html/rfc7677

Can you solve it?

Thanks in advance.

**Comment by rcpacini** [comment]
Updated SCRAM-SHA-256 reference to its successor RFC7677

**Comment by Neustradamus** [comment]
@rcpacini: Thanks for the update :)

A little mistake, you have inversed letters: "SCARM" one time.
