### ISSUE TITLE
Can you add topics in this repository?

### ISSUE THREAD

**Issue by Neustradamus** [rcpacini/labview_hashlib#2]
@rcpacini: I wish you a Happy New Year!

Can you add topics for supported algorithms in this repository?
- scram
- scram-sha-256
- pbkdf2-sha-256
- hmac-sha-256
- sha-256
- base64

Thanks in advance.

**Comment by rcpacini** [comment]
Thanks for the feedback, What kind of additional information are you looking for?
     The RFC's (linked in the README.md) are a great place to get detailed information on each algorithm. The LabVIEW VI's also have labels throughout the code for context help. One of the primary reasons for building this library was to communicate and authenticate a Rethink Database (RethinkDB) connection:
https://rethinkdb.com/docs/writing-drivers/
RethinkDB has a good overview of the SCRAM-SHA-256 authentication protocol.

**Comment by Neustradamus** [comment]
@rcpacini: Thanks for your reply!
On this place, at right, you must to click on the gear to update topics (add missing) ^^
- https://github.com/rcpacini/LabVIEW-Hashlib

**Comment by rcpacini** [comment]
Topics added, cheers.

**Comment by Neustradamus** [comment]
@rcpacini: I think there was a bug, I see only: "cryptography base64 authentication hash crc sha256 crc32 crc16 sha256-crypt crc8"
