### ISSUE TITLE
2019 Version

### ISSUE THREAD

**Issue by AdagioSostenutto** [rcpacini/labview_hashlib#4]
Hi, I would like to try your library but I do not have access to the 2021 LabVIEW version. 

Could you be so kind to save the project in 2019 version?

Appreciate your help.

Thank you.

Kind regards.

**Comment by rcpacini** [comment]
Saved project in LabVIEW 2018 (for legacy support) here:
[LabVIEW-Hashlib LabVIEW 2018.zip](https://github.com/rcpacini/LabVIEW-Hashlib/blob/master/Builds/LabVIEW-Hashlib%20LabVIEW%202018.zip)
